### ISSUE TITLE
Video preview layout issues

### ISSUE THREAD

**Issue by mjeronimo** [space-ros/spaceros.org#1]
When viewing the video previews (Categories | Videos), the preview windows should be laid out in a grid. Currently, the windows lay out strangely, depending on the height of the different windows:

![1](https://user-images.githubusercontent.com/865395/200404126-7371c8e0-6e87-47a8-b3cc-615f167c566f.png)

**Comment by german-e-mas** [comment]
PR: https://github.com/mjeronimo/pelican-fh5co-marble/pull/2

**Comment by german-e-mas** [comment]
The changes were merged and deployed.
