### ISSUE TITLE
[Mobile] Sidenav to cover all the space

### ISSUE THREAD

**Issue by german-e-mas** [space-ros/spaceros.org#16]
Related to #6 

Make the sidenav as wide as the screen on Mobile devices.

Check the feasibility of this:
- The hamburguer icon should transform to a cancel and be on top of the expanded sidenav as well.
- We shouldn't be able to scroll horizontally while the sidenav is open. It should be an overlay.

In case it is very difficult to implement this in the current theme, perhaps it's a good idea to leave the current behavior. FYI @mjeronimo . I'll let you know how this goes.

**Comment by mjeronimo** [comment]
Yes, it's OK to leave as-is if it seems like a lot of work. A related thing is that the hamburger sometimes doesn't show up because of the background image color (black on black). Any way to adapt to the background image color?

**Comment by german-e-mas** [comment]
While the sidenav width can be changed on mobile views, the button position is problematic.

![spaceROS-toggle-btn-003](https://user-images.githubusercontent.com/14120807/206543360-1aa901e2-2794-4356-bb2d-a8e789f6e2c4.gif)

Given the way the icon is built, it will be very complicated to come up with a solution for it to look good in this case.

I think the width can be left as it currently is. PR https://github.com/mjeronimo/pelican-fh5co-marble/pull/6 solves it's color issue.

Let me know what do you think @mjeronimo

**Comment by mjeronimo** [comment]
Sounds good to me. We can close this one.

**Comment by german-e-mas** [comment]
https://github.com/mjeronimo/pelican-fh5co-marble/pull/6 has been merged. I'll proceed to close this one!
