### ISSUE TITLE
The Read More buttons are not responsive

### ISSUE THREAD

**Issue by mjeronimo** [space-ros/spaceros.org#2]
When the window gets smaller, the Read More buttons are not updated:

![2](https://user-images.githubusercontent.com/865395/200404506-76390a17-89d1-4029-b297-9b995172c047.png)

Instead, the buttons should adjust to the screen resolution.

**Comment by german-e-mas** [comment]
Note: This needs to be addressed at the [Theme](https://github.com/mjeronimo/pelican-fh5co-marble) level. I'll create a PR there.

**Comment by german-e-mas** [comment]
PR: https://github.com/mjeronimo/pelican-fh5co-marble/pull/1

**Comment by german-e-mas** [comment]
The changes were merged and deployed.
