### ISSUE TITLE
Use smaller Space ROS icon for small window sizes

### ISSUE THREAD

**Issue by mjeronimo** [space-ros/spaceros.org#3]
The Space ROS icon should change to the logo only (no text) for small screen dimensions.

Currently, the icon is truncated:

![3](https://user-images.githubusercontent.com/865395/200404839-b750658c-b572-43c1-af85-44335b09cff6.png)

Instead, the page should use the logo without the Space ROS text.

**Comment by mjeronimo** [comment]
Perhaps something like this:

![4](https://user-images.githubusercontent.com/865395/200417402-690ffe11-8d0b-498e-bac9-ea3416e5aaf1.png)

**Comment by german-e-mas** [comment]
One thing we can also do is to set the background color of it. This way, it won't look like a square image and cover all the width of the sidenav.

Something like:

![localhost_8081_](https://user-images.githubusercontent.com/14120807/201432373-999b195d-0b27-48c2-ad69-0f44fa457022.png)

(Mock image)

What do you think?

**Comment by mjeronimo** [comment]
@german-e-mas Yes, that looks nice. Good idea.

**Comment by german-e-mas** [comment]
The related changes (https://github.com/mjeronimo/pelican-fh5co-marble/pull/4 and https://github.com/space-ros/spaceros.org/pull/10) were merged and deployed.
