### ISSUE TITLE
The search functionality is not working on deployed site

### ISSUE THREAD

**Issue by mjeronimo** [space-ros/spaceros.org#4]
When deployed on github pages, the base URL is https://space-ros.github.io/spaceros.org/. The search plugin uses paths to its search results using URLs like /pages/faq.html. The resulting (bad) URL is: https://space-ros.github.io/pages/faq.html instead of the correct https://space-ros.github.io/spaceros.org/pages/faq.html.

This will likely be OK when the site is deployed using the space.ros.org domain name.

**Comment by german-e-mas** [comment]
Now that the site is deployed at https://space.ros.org, the Search functionallity works as intended.

I'll leave this issue open. Feel free to close it once you try it out @mjeronimo .

**Comment by mjeronimo** [comment]
Looks good to me, thanks. Closing.
