### ISSUE TITLE
Deploy site on space.ros.org

### ISSUE THREAD

**Issue by mjeronimo** [space-ros/spaceros.org#7]
The Space ROS website is currently deployed on github Pages at https://space-ros.github.io/spaceros.org/. It should be available on space.ros.org. @nuclearsandwich is working on setting up the domain name. 

Other URLs, like spaceros.org, should also redirect to space.ros.org (Steven has the info on the domain names).

**Comment by nuclearsandwich** [comment]
I swapped the assignees here since this is on me and our hosting providers. We have some other DNS changes that require some additional infrastructure setup to complete. Once those are wrapped this should be a fairly straightforward change.

**Comment by mjeronimo** [comment]
Sounds good, thanks.

**Comment by german-e-mas** [comment]
The website is now up now at https://space.ros.org, with HTTPS working as intended.

Thanks @nuclearsandwich for the DNS related changes!
