### ISSUE TITLE
Update the site for real contact info

### ISSUE THREAD

**Issue by mjeronimo** [space-ros/spaceros.org#8]
The Contact information should be correct and functional.

**Comment by german-e-mas** [comment]
Currently contact information is:
- info@spaceros.org
- Mt. View, CA
- +1 650-450-9681

Is this accurate?

---

As for functional, do you have access to info@spaceros.org to determine whether the contact messages sent through the page are received?

**Comment by mjeronimo** [comment]
@german-e-mas The phone number and city are accurate, per https://www.openrobotics.org/contact. The main thing was: what email address to use. "info@spaceros.org" is fictitious. Perhaps @nuclearsandwich has an idea here.

**Comment by mjeronimo** [comment]
The email address is fixed by #11. Now, at least all of the information is correct. Perhaps in the future there will be Space ROS-specific contact info. Closing.
